<Project>
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <Deterministic>true</Deterministic>
        <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --config-file &quot;$(MSBuildThisFileDirectory)tests\testconfig.json&quot;</TestingPlatformCommandLineArguments>
    </PropertyGroup>
</Project>
